name: Manual Sender

on:
  schedule:   
    - cron: '0 1-23 * * *'
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-and-notify:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Nécessaire pour pouvoir faire le commit

    steps:
      - name: Checkout du repo
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installation des dépendances
        run: npm install @actions/core

      - name: Exécution du script main.js
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: node main.js

      - name: Commit & Push du fichier anti-redondance
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # On ajoute uniquement le fichier sent_events.json
          git add sent_events.json
          
          # On vérifie s'il y a de vraies modifications sur ce fichier spécifique
          if git diff --staged --quiet sent_events.json; then
            echo "[INFO] Aucun changement dans sent_events.json. Pas de commit nécessaire."
          else
            echo "[INFO] Nouveaux événements enregistrés. Commit en cours..."
            git commit -m "chore: mise à jour des alertes envoyées [skip ci]"
            git push
          fi
